### PR TITLE
Vector testing example

### PR DESCRIPTION
**Pull request by sovesti**
also added license headers

### CODE REVIEW

**Review by zelenyhleb — APPROVED** [review]
Looks great!

**Review by ruspl-afed — CHANGES_REQUESTED** [review]
Let's leave fancy_ptr* files unchanged for this PR: do you need them for tests?

And please keep original author in the license header
"Vladimir Ivanov (ArSysOp)"

**Review by ruspl-afed — APPROVED** [review]
Looks much better

**Review by zelenyhleb — APPROVED** [review]
Diff is now ok. LGTM

**Review by ruspl-afed — APPROVED** [review]

**Pull request merged**
